services:
  mikrotik-proxy-manager:
    image: mikrotik-proxy-manager:0.1.0
    container_name: mikrotik-proxy-manager
    restart: unless-stopped
    command: ["python", "-m", "mikrotik-proxy-manager"]
    environment:
      LOG_LEVEL: "INFO"
      MIKROTIK_LOG_FILE: "logs.0.txt"
    volumes:
      - ./logs:/srv/logs
  
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/config:/etc/traefik/dynamic"
      - "./traefik/acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].main=akmalov.com"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.akmalov.com"

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"
