services:
  mikrotik-proxy-manager:
    image: ghcr.io/akmalovaa/mikrotik-proxy-manager:latest
    container_name: mikrotik-proxy-manager
    restart: unless-stopped
    command: ["python", "-m", "mikrotik_proxy_manager"]
    environment:
      LOG_LEVEL: "INFO"
      MIKROTIK_LOG_FILE: "logs.0.txt"
      TRAEFIK_CONFIGS_PATH: "./configs"
    volumes:
      - ./logs:/srv/logs

  traefik:
    image: traefik:3.3.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/config:/etc/traefik/dynamic"
      - "./traefik/acme.json:/acme.json"
