services:
  mikrotik-proxy-manager:
    # image: mikrotik-proxy-manager:latest
    build:
      dockerfile: Dockerfile
    container_name: mikrotik-proxy-manager
    restart: unless-stopped
    # command: ["python", "-m", "mikrotik_proxy_manager"]
    command: ["tail", "-f", "/dev/null"]
    environment:
      LOG_LEVEL: "DEBUG"
      MIKROTIK_LOG_FILE: "logs.0.txt"
      TRAEFIK_CONFIGS_PATH: "./configs"
    volumes:
      - .:/srv

