global:
  checkNewVersion: false
  sendAnonymousUsage: false

http:
  routers:
    traefik-secure:
      tls:
        certResolver: letsEncrypt

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false
  websecure:
    address: :443
    proxyProtocol:
      trustedIPs:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

providers:
  file:
    directory: /configs
    watch: true

api:
  dashboard: true
  insecure: true
  debug: false

log:
  level: INFO
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

ping: {}  # Healtcheck for traefik default port 8080

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  letsEncrypt:
    acme:
      email: admin@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
